# This workflow will test on Deno lastest stable major and canary
# see https://github.com/marketplace/actions/setup-deno for details
name: Deno CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.40 # Run with latest stable Deno.
      - run: deno fmt --check
      - run: deno lint
      - run: deno test -A
